set -g prefix C-s
unbind r

set -g default-terminal "tmux-256color"
set -ga terminal-features ",xterm-kitty:RGB,foot:RGB"
set -g default-shell /bin/zsh
set -gq allow-passthrough on
set -g visual-activity off
set -g mouse on
set -g base-index 1
set -sg escape-time 0

setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel

set-option -g status-position bottom
set -g status-right ' #[fg=color249]#(date +"%I:%M%p %d/%m/%Y")#[default] '
set -g status-style "fg=color249,bg=color233"
set -g mode-style "fg=color0,bg=#5661ad"
set -g window-status-current-style "fg=color255,bg=#5661ad"
set -g pane-active-border-style 'fg=color238'
set -g pane-border-style 'fg=color238'

bind r source-file ~/.tmux.conf \; display-message "Config reloaded"
bind C-j display-popup -E "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"
bind-key C-n command-prompt -p "New session name:" "new-session -s '%%'"
bind \\ split-window -h
bind - split-window -v
bind -n M-p previous-window
bind -n M-n next-window

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
run '~/.tmux/plugins/tpm/tpm'
