## name: Blueberry Mango
## author: janbridley
## license: MIT
## upstream: https://github.com/janbridley/blueberry-mango

foreground #feffe0
background #181321
selection_foreground #f4f4f4
selection_background #1e0623
cursor #d28133
cursor_text_color #fefefe
url_color #ea9649
active_border_color #54b99d
inactive_border_color #171320
bell_border_color #f0a2a3
active_tab_foreground #feffe0
active_tab_background #171320
inactive_tab_foreground #4a5060
inactive_tab_background #171320
tab_bar_background #171320
color0 #16141e
color1 #ed7481
color2 #54b99d
color3 #e0c750
color4 #6ee4de
color5 #ca476a
color6 #6fb3bf
color7 #f1f1f1
color8 #4a5060
color9 #f0a2a3
color10 #a0c180
color11 #f5e47d
color12 #abfcf3
color13 #cc75d0
color14 #c7f1fc
color15 #fefefe
